2020-07-26 08:55:11,512::ThreadPoolExecutor-0_0::INFO::root::81::Downloading:
2020-07-26 08:55:11,514::ThreadPoolExecutor-0_0::ERROR::root::85::website: , download error:Invalid URL '': No schema supplied. Perhaps you meant http://?
Traceback (most recent call last):
  File "e:\MyProjects\plscraper\plscraper\plscraper.py", line 83, in download_url
    response = requests.get(url, headers=headers.random_header())
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\sessions.py", line 449, in prepare_request
    p.prepare(
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\models.py", line 388, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?
2020-07-26 08:55:11,516::ThreadPoolExecutor-0_0::INFO::root::81::Downloading:
2020-07-26 08:55:11,516::ThreadPoolExecutor-0_0::ERROR::root::85::website: , download error:Invalid URL '': No schema supplied. Perhaps you meant http://?
Traceback (most recent call last):
  File "e:\MyProjects\plscraper\plscraper\plscraper.py", line 83, in download_url
    response = requests.get(url, headers=headers.random_header())
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\sessions.py", line 449, in prepare_request
    p.prepare(
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\models.py", line 388, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:\MyProjects\plscraper\plscraper\plscraper.py", line 83, in download_url
    response = requests.get(url, headers=headers.random_header())
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\sessions.py", line 449, in prepare_request
    p.prepare(
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\models.py", line 388, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?
2020-07-26 08:55:11,516::ThreadPoolExecutor-0_0::INFO::root::81::Downloading:
2020-07-26 08:55:11,516::ThreadPoolExecutor-0_0::ERROR::root::85::website: , download error:Invalid URL '': No schema supplied. Perhaps you meant http://?
Traceback (most recent call last):
  File "e:\MyProjects\plscraper\plscraper\plscraper.py", line 83, in download_url
    response = requests.get(url, headers=headers.random_header())
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\sessions.py", line 449, in prepare_request
    p.prepare(
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\models.py", line 388, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:\MyProjects\plscraper\plscraper\plscraper.py", line 83, in download_url
    response = requests.get(url, headers=headers.random_header())
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\sessions.py", line 449, in prepare_request
    p.prepare(
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\models.py", line 388, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:\MyProjects\plscraper\plscraper\plscraper.py", line 83, in download_url
    response = requests.get(url, headers=headers.random_header())
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\sessions.py", line 449, in prepare_request
    p.prepare(
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\models.py", line 388, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?
2020-07-26 08:55:11,517::ThreadPoolExecutor-0_0::INFO::root::81::Downloading:
2020-07-26 08:55:11,517::ThreadPoolExecutor-0_0::ERROR::root::85::website: , download error:Invalid URL '': No schema supplied. Perhaps you meant http://?
Traceback (most recent call last):
  File "e:\MyProjects\plscraper\plscraper\plscraper.py", line 83, in download_url
    response = requests.get(url, headers=headers.random_header())
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\sessions.py", line 449, in prepare_request
    p.prepare(
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\models.py", line 388, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:\MyProjects\plscraper\plscraper\plscraper.py", line 83, in download_url
    response = requests.get(url, headers=headers.random_header())
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\sessions.py", line 449, in prepare_request
    p.prepare(
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\models.py", line 388, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:\MyProjects\plscraper\plscraper\plscraper.py", line 83, in download_url
    response = requests.get(url, headers=headers.random_header())
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\sessions.py", line 449, in prepare_request
    p.prepare(
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\models.py", line 388, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:\MyProjects\plscraper\plscraper\plscraper.py", line 83, in download_url
    response = requests.get(url, headers=headers.random_header())
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\sessions.py", line 449, in prepare_request
    p.prepare(
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\models.py", line 388, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?
2020-07-26 08:55:11,518::ThreadPoolExecutor-0_0::INFO::root::88::Downloaded:
2020-07-26 08:55:11,859::ThreadPoolExecutor-0_0::INFO::root::81::Downloading:
2020-07-26 08:55:11,860::ThreadPoolExecutor-0_0::ERROR::root::85::website: , download error:Invalid URL '': No schema supplied. Perhaps you meant http://?
Traceback (most recent call last):
  File "e:\MyProjects\plscraper\plscraper\plscraper.py", line 83, in download_url
    response = requests.get(url, headers=headers.random_header())
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\sessions.py", line 449, in prepare_request
    p.prepare(
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\models.py", line 388, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?
2020-07-26 08:55:11,860::ThreadPoolExecutor-0_0::INFO::root::81::Downloading:
2020-07-26 08:55:11,860::ThreadPoolExecutor-0_0::ERROR::root::85::website: , download error:Invalid URL '': No schema supplied. Perhaps you meant http://?
Traceback (most recent call last):
  File "e:\MyProjects\plscraper\plscraper\plscraper.py", line 83, in download_url
    response = requests.get(url, headers=headers.random_header())
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\sessions.py", line 449, in prepare_request
    p.prepare(
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\models.py", line 388, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:\MyProjects\plscraper\plscraper\plscraper.py", line 83, in download_url
    response = requests.get(url, headers=headers.random_header())
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\sessions.py", line 449, in prepare_request
    p.prepare(
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\models.py", line 388, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?
2020-07-26 08:55:11,860::ThreadPoolExecutor-0_0::INFO::root::81::Downloading:
2020-07-26 08:55:11,861::ThreadPoolExecutor-0_0::ERROR::root::85::website: , download error:Invalid URL '': No schema supplied. Perhaps you meant http://?
Traceback (most recent call last):
  File "e:\MyProjects\plscraper\plscraper\plscraper.py", line 83, in download_url
    response = requests.get(url, headers=headers.random_header())
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\sessions.py", line 449, in prepare_request
    p.prepare(
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\models.py", line 388, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:\MyProjects\plscraper\plscraper\plscraper.py", line 83, in download_url
    response = requests.get(url, headers=headers.random_header())
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\sessions.py", line 449, in prepare_request
    p.prepare(
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\models.py", line 388, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:\MyProjects\plscraper\plscraper\plscraper.py", line 83, in download_url
    response = requests.get(url, headers=headers.random_header())
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\sessions.py", line 449, in prepare_request
    p.prepare(
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\models.py", line 388, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?
2020-07-26 08:55:11,861::ThreadPoolExecutor-0_0::INFO::root::81::Downloading:
2020-07-26 08:55:11,862::ThreadPoolExecutor-0_0::ERROR::root::85::website: , download error:Invalid URL '': No schema supplied. Perhaps you meant http://?
Traceback (most recent call last):
  File "e:\MyProjects\plscraper\plscraper\plscraper.py", line 83, in download_url
    response = requests.get(url, headers=headers.random_header())
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\sessions.py", line 449, in prepare_request
    p.prepare(
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\models.py", line 388, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:\MyProjects\plscraper\plscraper\plscraper.py", line 83, in download_url
    response = requests.get(url, headers=headers.random_header())
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\sessions.py", line 449, in prepare_request
    p.prepare(
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\models.py", line 388, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:\MyProjects\plscraper\plscraper\plscraper.py", line 83, in download_url
    response = requests.get(url, headers=headers.random_header())
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\sessions.py", line 449, in prepare_request
    p.prepare(
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\models.py", line 388, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:\MyProjects\plscraper\plscraper\plscraper.py", line 83, in download_url
    response = requests.get(url, headers=headers.random_header())
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\sessions.py", line 449, in prepare_request
    p.prepare(
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "E:\MyProjects\plscraper\venv\lib\site-packages\requests\models.py", line 388, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?
2020-07-26 08:55:11,862::ThreadPoolExecutor-0_0::INFO::root::88::Downloaded:
